tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "FelixKratz/formulae"

brew "yabai"
brew "skhd"

cask "arc"
cask "alacritty"
cask "raycast"
cask "obsidian"
cask "docker"

cask "font-sauce-code-pro-nerd-font"

brew "gnupg"
cask "gpg-suite"

brew "cmake"
brew "emscripten"
brew "node"
brew "java"
brew "boost"
brew "act"
brew "zoxide"
brew "fzf"
brew "shfmt"

brew "starship"
brew "sketchybar"
brew "borders"

