"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$nodejs\
$line_break\
$character\
"""

add_newline = false 

[character] 
success_symbol = '[➜](bold green)' 
error_symbol = '[➜](bold red)'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[cmd_duration]
format = ' [󱎫 $duration]($style) '

[username]
show_always = true
format = '[$user]($style) '

[directory]
fish_style_pwd_dir_length = 1
truncation_length = 1

[fill]
symbol = ' ' 

[nodejs]
format = '[$symbol($version )]($style)'

